Разметка всех страниц
htmlacademy-htmlcss/2051043-sedona-34 pull request #2
Opened 2022-05-24 11:31 UTC by GaryaevRuslan

добавил разметку

---
:mortar_board: [Разметка всех страниц](https://up.htmlacademy.ru/htmlcss/34/user/2051043/tasks/4)

:boom: https://htmlacademy-htmlcss.github.io/2051043-sedona-34/2/

2022-05-25 14:48 UTC, Ankhena requested changes

2022-05-25 14:48 UTC, Ankhena commented on index.html
> +    <img class="logo" src="#" alt="Логотип курорта Седона.">
Обычно логотип оборачивают ссылкой, ведущей на главную страницу. Посетители уже привыкли к такому поведению.

И эта ссылка входит в nav. (Но не должна попадать в список)

2022-05-25 14:48 UTC, Ankhena commented on index.html
> +      <a class="navigation-link" href="main.html" >О Седоне
У тебя файл с главной страницей сайта называется index.html, а ссылка ведет на какой-то неизвестный main.html

2022-05-25 14:48 UTC, Ankhena commented on index.html
> +        <a class="navigation-link" href="main.html" >Гостиницы
И тут аналогично: файл страницы каталога ты назвал catalog.html. Ссылку на него и нужно указывать тут.

2022-05-25 14:48 UTC, Ankhena commented on index.html
> +      <a class="navigation-link" href="#" > <span class="visually-hidden">Поиск
✳ Я бы не стала задавать одинаковые классы элементов обоих меню. Уж слишком сильно они различаются. 
Это не обязательно изменять сейчас, можешь оставить до  того момента, когда сам поймешь, что и тебе неудобно.

2022-05-25 14:48 UTC, Ankhena commented on index.html
> +    <h1 class="visually-hidden">Седона городок</h1>
Где-то тут должна быть картинка с текстом.
![2022-05-25_17-21-39](https://user-images.githubusercontent.com/20879307/170285073-8cf3a55a-52ef-4be3-8c8d-b78d880b291e.jpg)

Будет удобно сделать секцию с каким-то классом. например, intro. И в неё сложить скрытый заголовок h1 и  эту картинку. 
(Горы и зигзаг в разметку вставлять не нужно.)

2022-05-25 14:48 UTC, Ankhena commented on index.html
> +      <h2 class="visually-hidden">Преимущества</h2>
В макете есть видимый заголовок. У тебя он совсем потерялся. 
И еще в макете есть абзац с предложением рассмотреть 5 причин.
![Седона - секции на главной](https://user-images.githubusercontent.com/20879307/170286080-d968d486-f525-4f16-bcea-66fb53d399c5.jpg)

2022-05-25 14:48 UTC, Ankhena commented on index.html
> +        <li class="advantages-item">
В макете есть предложение рассмотреть 5 причин и дальше идет список из этих причин. 
Это значит, что и у тебя в коде элементов списка должно быть именно 5. 
Еда-жилье-сувениры это вложенный список в первую причину. 
![Седона - 5 причин](https://user-images.githubusercontent.com/20879307/170285982-e950d4d0-503d-43ff-930e-efd1958e2be3.jpg)

2022-05-25 14:48 UTC, Ankhena commented on index.html
> +                   </li>
✳ Тебе самому будет удобнее работать со структурой кода и будет меньше ошибок, если писать код "лесенкой". 
Форматирование кода доступно в VS Code с помощью следующих сочетаний клавиш:

- В Windows    
    Shift +Alt +F
    
- На Mac    
    Shift + Option +F
    
- В Ubuntu    
    Ctrl + Shift + I
    
![2022-05-25_17-26-55](https://user-images.githubusercontent.com/20879307/170286537-a256a7a8-40e1-4fac-b22e-ce5a80a5a684.jpg)
Закрывающий `</li>` должен оказываться строго под открывающим. Вложенные с отступом.

2022-05-25 14:48 UTC, Ankhena commented on index.html
> +      <input type="text" placeholder="Ваш email">
Input и button выпали из формы. 
Для проверки работоспособности можешь попробовать нажать на кнопку Подписаться. Должна открыться страница https://echo.htmlacademy.ru/ и на ней должно быть написано какие данные получил сервер.

2022-05-25 14:48 UTC, Ankhena commented on index.html
> +      <input type="text" placeholder="Ваш email">
Для доступности у инпутов должны быть подписи `<label>`, если их нет в макете, то скрытые.

2022-05-25 14:48 UTC, Ankhena commented on index.html
> +    <img class="footer-contacts-logo" src="#" alt="Логотип Html academy».">
Вокруг лого Академии должна быть ссылка, ведущая на Академию (куда конкретно написано рядом с макетом в Фигме)

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +  <body>
Всё что я написала про хедер для главной страницы актуально и для страницы каталога.

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +       <h2 class="main-title">Гостиницы Седоны</h2>
Скажи, зачем тут два почти одинаковых заголовка?

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +       <fieldset class="catalog-filter-group">
Фильтр - это форма, тег form

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +      <input class="control-input" type="checkbox" name="Parking" checked>
```
name="pool"
name="Parking"
name="WI-FI"
```
Будет гораздо удобнее работать с кодом, если все атрибуты будут в едином стиле. В данном случае, хорошо бы маленькими буквами.

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +
# label и input - есть рекомендации как их лучше использовать? Вкладывать инпут в лейбл или располагать рядом.

1. У одного инпута может быть несколько label
2. В конструкции
`label > (input + span)`
есть лишний тег
этот аргумент можно компенсировать идеей, что чаще всего инпут с лейблом хочется (или нужно) во что-то обернуть для стилизации
но так далеко не всегда.
А если есть список из инпутов+лейбл, то обертка уже и так есть готовая.
3. Из этого же: мы не можем обратится к родительскому label при разных состояниях инпута и творим дополнительный span.
А чем меньше элементов в DOM, тем лучше
4. Даже при вложенном в лейбл инпуте имеет смысл задавать for и id для читалок
Вот, кстати, MDN пишет:
*Однако даже в таких случаях лучше всё равно указывать атрибут `for`, так как некоторые вспомогательные технологии не распознают неявную связь между текстами-подсказками и виджетами.*
https://clck.ru/gerGW (ссылка на MDN)

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +          <legend class="catalog-filter-title">Стоимость Р</legend>
Символ рубля можно скопировать прямо из макета
`Стоимость, ₽:`

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +
Тут должны быть кнопки отправки и очистки формы. 
И конец самой формы.

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +        <select class="select-control" aria-label="Сортировка">
Обрати, пожалуйста, внимание на текст в макете

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +
В макете 3 варианта отображения результатов. У тебя вижу только два.

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +        <b class="product-card-price">Гостиница от 4000р ₽</b>
✳
```
 <a class="product-card-link" href="product.html">
          <img class="product-card-image" src="#" alt="Картинка">
          <h3 class="product-card-title">Amara Resort & SPA</h3>
        </a>
```
Можно получше:
Давай посмотрим в макет: на первый взгляд кажется, что это отличная идея, объединить в одну ссылку картинку и заголовок.
Да и вообще, разумно, что и заголовок и картинка должны быть кликабельными.

Но есть нюанс: дизайнер нарисовал кнопочки, меняющие вид всего списка. Правда, забыл нарисовать как будет выглядеть. Придется нам самим предположить.
![Седона - вид карточек](https://user-images.githubusercontent.com/20879307/170289522-3882c4e5-58c8-4336-a73d-a0564b2800a3.jpg)

Я думаю, что как-то так 👆

И тебе самому же будет не удобно делать сетку, если картинка с заголовком останутся в одной ссылке

Так что лучше разбить на две.
И  задать им атрибуты tabindex: -1, чтобы её нельзя было выбрать с клавиатуры.
Но это забегая вперед.

Потому что иначе будут три ссылки ведущие в одно место. И пользователю без мышки придется делать по 2 лишних таба на каждую карточку.
Если гостиниц найдется сотня, то можно представить, что скажет пользователь.

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +      <ul class="product-list">
А ведь список гостиниц тут не закончился. 
Значит ul закрывается не тут, а после всех гостиниц.

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +    <b class="product-card-price">Гостиница от 2500р ₽</b>
Много букв `p`, в макете тут нет символа рубля, просто буква р. 

`Гостиница от 2500р ₽`
Посмотри, в макете видно, что это два отдельных тега.

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +    <a class="product-card-button button" href="#">Подробнее</a>
`b` это тег не несущий семантической нагрузки, но зато он тащит с собой форматирование, возможно никому не нужное. 
Лучше заменить на просто `<p>` и потом стилизовать как нужно.

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +    <a class="product-card-button button" href="#">Избранное</a>
Где-то потерялись звезды и рейтинг. 

**Звезды** это какой-то элемент, на твой выбор, у которого есть текстовая составляющая, span с visually-hidden
и есть 2 класса, один общий и один уникальный, определяющий количество звезд.
Этот класс указывает ширину, в зависимости от которой в фон этого блока помещается разное количество звезд.

2022-05-25 14:48 UTC, Ankhena commented on catalog.html
> +    </section>
А где пагинация?

2022-05-27 04:41 UTC, GaryaevRuslan commented on catalog.html
> +
здесь что то нужно переделать?

2022-05-31 15:04 UTC, Ankhena requested changes

2022-05-31 15:04 UTC, Ankhena commented on index.html
> +    <section class="intro">
Что это за пустая секция?
В ней должны быть:
1. Заголовок h1 с текстом типа "Добро пожаловать в Седону"
2. Картинка, так которая `<img src="#" alt="Sedona.">`

2022-05-31 15:04 UTC, Ankhena commented on index.html
> +        <h1>Седона небольшой городок в Аризоне заслуживающий большего</h1>
Это h2

2022-05-31 15:04 UTC, Ankhena commented on index.html
> +        <h2 class="visually-hidden">Преимущества</h2>
Это `<h2 class="visually-hidden">Преимущества</h2>` лишнее, у этой секции уже есть заголовок.

2022-05-31 15:04 UTC, Ankhena commented on index.html
> +          </ul>
Внешний `ul` не должен тут заканчиваться. 
Ведь причин 5. Значит, в этом списке должно быть 5 элементов `li`

А внутренний список еда-жилье-сувениры - нужно вложить внутрь первого li из большого списка.

2022-05-31 15:04 UTC, Ankhena commented on index.html
> +        <label class="visually-hidden" for="email"></label>
Потерялся текст подписи.

2022-05-31 15:04 UTC, Ankhena commented on catalog.html
> +    <a href="page/index.html"><img class="logo" src="#" alt="Логотип курорта Седона."></a>
Логотип является элементом nav, но не должен быть включен в список.

2022-05-31 15:04 UTC, Ankhena commented on catalog.html
> +        </li>
В хлебных крошках **два** элемента. 
Значит, в списке должно быть **два** li, а не один как сейчас.

2022-05-31 15:04 UTC, Ankhena commented on catalog.html
> +      <form>
Для тега form нужно добавить атрибут method с соответствующим значением и атрибут `action="https://echo.htmlacademy.ru/"`

2022-05-31 15:04 UTC, Ankhena commented on catalog.html
> +      </form>
Разве форма заканчивается тут?
Посмотри, пожалуйста, на макет. Мы с тобой рисовали где форма начинается и где заканчивается.
Вот она. 
![2022-05-31_17-55-39](https://user-images.githubusercontent.com/20879307/171204428-4d73bae4-e678-43df-a4a2-49c9329af3b8.png)
 Все что на макете внутри красной рамки - это всё содержимое тега form. 
 
 А секции там нет вообще, вместо section там должен быть просто div для того, чтобы было чему задать фон. Обвела его зеленым:
![2022-05-31_17-57-43](https://user-images.githubusercontent.com/20879307/171204862-a0f7f6b2-218b-4daa-923b-4c7393f03679.png)

2022-05-31 15:04 UTC, Ankhena commented on catalog.html
> +        <option value="popular">Сначала популярное</option>
Посмотри, пожалуйста, что написано в макете обрати внимание, в каком роде. 
В твоей верстке должно быть точно также.

2022-05-31 15:04 UTC, Ankhena commented on catalog.html
> +        <li class="pagination-item">
Зачем этот пустой li?

2022-05-31 15:04 UTC, Ankhena commented on catalog.html
> +        </li>
У тебя в пагинации есть страницы 1, 2, 3, 4, 5, а в макете вот так:
![2022-05-31_18-01-15](https://user-images.githubusercontent.com/20879307/171205695-c143e27b-abe0-4ed9-b1a2-eebfdfed8b42.png)
Приведи, пожалуйста, в соответствие.

2022-05-31 15:04 UTC, Ankhena commented on catalog.html
> +      <button class="button pagination-show-more" type="button">Показать ещё</button>
Откуда эта кнопка?

2022-05-31 15:04 UTC, Ankhena commented on catalog.html
> +    </section>
После пагинации в макете нарисован select с выбором по сколько гостиниц показывать на странице. Его тоже нужно разметить.

2022-06-04 07:27 UTC, merged